directory: /mnt/media/Audio/Music
plugins: chroma fromfilename fetchart discogs lastgenre web convert
import:
  move: yes
  quiet_fallback: skip
  log: ~/.cache/beets/import.log
lastgenre:
  canonical: ''
